annotations:
  licenses: MIT
  group: xyz.jiangsier
apiVersion: v2
appVersion: latest
dependencies:
  - condition: bitnami.mysql.enabled
    name: mysql
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - mysql
      - sql
      - database
    version: 10.x.x
  - condition: bitnami.redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - redis
      - keyvalue
      - database
    version: 19.x.x
description: A Helm chart for jiangsier-archetype-demo
maintainers:
- email: leiyi.jp@gmail.com
  name: Kelvin Jiang
  url: https://github.com/jiangsier-xyz
name: jiangsier-archetype-demo
type: application
version: 0.1.1
