annotations:
  licenses: Apache-2.0
  group: xyz.jiangsier
apiVersion: v1
appVersion: latest
dependencies:
  - condition: mysql.enabled
    name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    tags:
      - backend
      - mysql
      - sql
      - database
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.x.x
    tags:
      - backend
      - redis
      - keyvalue
      - database
description: A Helm chart for jiangsier-archetype-demo
maintainers:
- email: leiyi.jp@gmail.com
  name: Kelvin Jiang
  url: https://github.com/jiangsier-xyz
name: jiangsier-archetype-demo
type: application
version: 0.0.1
