redis:
  datasource:
    url: redis://localhost:6379
    password: hello1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accounts?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hello1234
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 'fakeId'
            clientSecret: 'fakeSecret'
