# 10 seconds cache
# NOTE: Because the cache is often invalidated,
# it is recommended to set "sync" to true to prevent cache breakdown as
# @Cacheable(cacheNames = "shortPeriod", sync = true...)
shortPeriod:
  ttl: 10000
  maxIdleTime: 5000

# 5 minutes cache
middlePeriod:
  ttl: 300000
  maxIdleTime: 150000

# 1 hour cache
longPeriod:
  ttl: 3600000
  maxIdleTime: 1800000
